namespace KodivaFooFuu.Core.Interfaces;

/// <summary>
/// Rule that can match a number and provide output text when matched.
/// </summary>
public interface IRule
{
    /// <summary>
    /// Determines whether the specified number satisfies the criteria defined by the implementation.
    /// </summary>
    /// <param name="number">The number to evaluate against the matching criteria.</param>
    /// <returns>true if the number matches the criteria; otherwise, false.</returns>
    bool Matches(int number);

    /// <summary>
    /// Gets the output generated by the operation.
    /// </summary>
    string Output { get; }
}
